"""Client mutations: add, edit, delete.

The read and write shapes differ, and that asymmetry is the whole reason this
module exists. `clients/get/:email` answers a wrapper — the client object plus
its attachments and usage — while `clients/update/:email` wants the bare client
object, flat. Send the wrapper back and the panel accepts it, finds none of the
fields where it expects them, and stores their zero values instead.
"""

from __future__ import annotations

from .. import api, render, snapshot

help = "create, edit and delete clients"

# Xray understands these and nothing else. The panel stores whatever string it is
# given without checking, so a typo is accepted, saved and served - and the
# client simply fails to connect, with the panel showing it as perfectly fine
KNOWN_FLOWS = {"", "xtls-rprx-vision", "xtls-rprx-vision-udp443"}

# Fields a caller may set directly. Anything not listed is either derived,
# a credential the panel owns, or a link managed through attach/detach.
EDITABLE = {
    "enable": ("bool", "whether the client may connect"),
    "flow": ("str", "XTLS flow, e.g. xtls-rprx-vision; empty on non-Vision inbounds"),
    "totalGB": ("int", "traffic limit in bytes, 0 for unlimited"),
    "expiryTime": ("int", "expiry as unix milliseconds, 0 for never"),
    "limitIp": ("int", "simultaneous addresses allowed, 0 for unlimited"),
    "comment": ("str", "free-text note"),
    "tgId": ("int", "Telegram id; must be a number, a string rejects the request"),
    "reset": ("int", "traffic reset cycle in days, 0 for none"),
}


def _coerce(name: str, raw: str):
    kind = EDITABLE[name][0]
    if kind == "bool":
        lowered = raw.strip().lower()
        if lowered in {"true", "yes", "1", "on"}:
            return True
        if lowered in {"false", "no", "0", "off"}:
            return False
        raise ValueError(f"{name}: expected true or false, got {raw!r}")
    if kind == "int":
        try:
            return int(raw)
        except ValueError as error:
            raise ValueError(f"{name}: expected a number, got {raw!r}") from error
    return raw


def _reader(client, email: str):
    def read() -> dict:
        wrapper = client.get(api.path("clients", "get", email))
        if not isinstance(wrapper, dict) or "client" not in wrapper:
            raise snapshot.MutationError(
                f"unexpected shape for client {email!r}: {sorted(wrapper)[:6]}"
            )
        return dict(wrapper["client"])

    return read


# Read as a string, written as a list of strings. Determined by round-tripping
# a client field by field: `forwardedPorts` looks identical when read and is a
# string on both paths, so guessing by shape rather than testing gets it wrong.
LIST_FIELDS = ("allowedIPs",)


def _for_write(obj: dict) -> dict:
    """Translate the read shape into the write shape.

    The panel does not answer in the shape it accepts, and each mismatch is a
    type error rather than a silent one, so a faithful round trip has to convert:
    `id` carries the row's numeric key when read and the client's UUID when
    written, and the list-valued fields come back as strings.
    """
    body = dict(obj)
    if isinstance(body.get("id"), int) and body.get("uuid"):
        body["id"] = body["uuid"]
    for name in LIST_FIELDS:
        value = body.get(name)
        if isinstance(value, str):
            body[name] = [part.strip() for part in value.split(",") if part.strip()]
    return body


def _writer(client, email: str):
    def write(obj: dict) -> None:
        # Flat, whole, every time: the endpoint replaces the record.
        client.post(api.path("clients", "update", email), body=_for_write(obj))

    return write


def register(parser) -> None:
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")

    fields = sub.add_parser("fields", help="what may be set, and what it means")
    fields.set_defaults(needs_panel=False)

    setter = sub.add_parser("set", help="change fields, verifying nothing else moved")
    setter.add_argument("email")
    setter.add_argument(
        "assignments",
        nargs="+",
        metavar="FIELD=VALUE",
        help="for example enable=false totalGB=53687091200",
    )

    add = sub.add_parser("add", help="create a client on one or more inbounds")
    add.add_argument("email")
    add.add_argument("--inbound", type=int, action="append", required=True)
    add.add_argument("--flow", default="", help="pass explicitly; add never sets it")
    add.add_argument("--uuid", help="client UUID; generated by the panel when absent")
    add.add_argument("--total-gb", type=int, default=0)
    add.add_argument("--expiry-ms", type=int, default=0)
    add.add_argument("--comment", default="")

    delete = sub.add_parser("del", help="delete a client and its traffic rows")
    delete.add_argument("email")
    delete.add_argument(
        "--keep-traffic",
        action="store_true",
        help="preserve counters instead of removing them with the client",
    )
    delete.add_argument("--yes", action="store_true", help="skip the confirmation")


def run(args, client) -> int:
    if args.command == "fields":
        rows = [
            {"field": name, "type": kind, "meaning": meaning}
            for name, (kind, meaning) in sorted(EDITABLE.items())
        ]
        print(render.table(rows, ["field", "type", "meaning"]))
        return 0

    if args.command == "set":
        changes = {}
        for assignment in args.assignments:
            if "=" not in assignment:
                print(f"not a FIELD=VALUE pair: {assignment}")
                return 2
            name, _, raw = assignment.partition("=")
            if name not in EDITABLE:
                print(f"not editable: {name}. See: xui client-edit fields")
                return 2
            try:
                changes[name] = _coerce(name, raw)
            except ValueError as error:
                print(str(error))
                return 2
            if name == "flow" and changes[name] not in KNOWN_FLOWS:
                print(
                    f"warning: {changes[name]!r} is not a flow Xray knows. The panel "
                    f"stores it anyway and the client will fail to connect. "
                    f"Known: {', '.join(sorted(f or '(none)' for f in KNOWN_FLOWS))}"
                )

        try:
            applied = snapshot.apply_and_verify(
                _reader(client, args.email), _writer(client, args.email), changes
            )
        except snapshot.MutationError as error:
            print(f"REFUSED: {error}")
            return 1

        if not applied:
            print("no change (the values were already set)")
            return 0
        print("applied:")
        print(applied.describe(mask=lambda k, v: v))
        return 0

    if args.command == "add":
        body = {
            "client": {
                "email": args.email,
                "enable": True,
                # The panel never sets a flow on create, so a Vision inbound
                # gets a client that cannot connect unless it is named here.
                "flow": args.flow,
                "totalGB": args.total_gb,
                "expiryTime": args.expiry_ms,
                "comment": args.comment,
            },
            "inboundIds": args.inbound,
        }
        if args.uuid:
            body["client"]["id"] = args.uuid
        client.post("clients/add", body=body)

        created = _reader(client, args.email)()
        if args.flow and args.flow not in KNOWN_FLOWS:
            print(
                f"warning: {args.flow!r} is not a flow Xray knows; the panel accepted "
                "it without checking and the client will not connect"
            )
        if args.flow and created.get("flow") != args.flow:
            print(
                f"warning: asked for flow {args.flow!r} but the panel stored "
                f"{created.get('flow')!r} - the inbound may not support it"
            )
        print(f"created {args.email} on inbound(s) {', '.join(map(str, args.inbound))}")
        return 0

    if args.command == "del":
        if not args.yes:
            print(f"about to delete client {args.email!r} and its traffic rows.")
            print("re-run with --yes to proceed.")
            return 2
        query = {"keepTraffic": "1"} if args.keep_traffic else None
        client.post(api.path("clients", "del", args.email), query=query)
        print(f"deleted {args.email}")
        return 0

    print(f"unknown command: {args.command}")
    return 2
